EBookApp/EBookApp/Controllers/AboutController.cs
using EBook.Entities.Models;
using Microsoft.AspNetCore.Mvc;

namespace EBookApp.Controllers
{
    public class AboutController : Controller
    {
        EBookDbContext context = new EBookDbContext();

        public IActionResult Index()
        {
            return View();
        }
    }
}

EBookApp/EBookApp/Controllers/BookCategoryController.cs
using Microsoft.AspNetCore.Mvc;

namespace EBookApp.Controllers
{
	public class BookCategoryController : Controller
	{
        public IActionResult Roman()
        {
            return View();
        }

        public IActionResult Tarih()
        {
            return View();
        }

        public IActionResult BilimKurgu()
        {
            return View();
        }

        public IActionResult KisiselGelisim()
        {
            return View();
        }

        public IActionResult CizgiRoman()
        {
            return View();
        }

        public IActionResult Hikaye()
        {
            return View();
        }

        public IActionResult Ani()
        {
            return View();
        }
    }
}

EBookApp/EBookApp/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;

namespace EBookApp.Controllers
{
    public class BookController : Controller
    {
        public IActionResult SavasVeBaris()
        {
            return View();
        }
    }
}

EBookApp/EBookApp/Controllers/ContactController.cs
using EBook.Entities.Models;
using Microsoft.AspNetCore.Mvc;

namespace EBookApp.Controllers
{
    public class ContactController : Controller
    {
        EBookDbContext context = new EBookDbContext();

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(Contact contact)
        {
            if(User == null)
            {
              
            }
            return View(contact);
        }
    }
}

EBookApp/EBookApp/Controllers/LibraryController.cs
using EBook.Entities.Models;
using Microsoft.AspNetCore.Mvc;

namespace EBookApp.Controllers
{
    public class LibraryController : Controller
    {
        EBookDbContext context = new EBookDbContext();

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]

        public async Task<IActionResult> Index(Library library)
        {
            return View();
        }
    }
}

EBookApp/EBookApp/Views/BookCategory/Ani.cshtml
@model EBook.Entities.Models.BookCategory
@{
    Layout = null;
}

<!DOCTYPE HTML>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Muhayyel-Anı</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="" />
	<meta name="keywords" content="" />
	<meta name="author" content="" />

	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content="" />
	<meta property="og:image" content="" />
	<meta property="og:url" content="" />
	<meta property="og:site_name" content="" />
	<meta property="og:description" content="" />
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="favicon.ico">

	<link href="https://fonts.googleapis.com/css?family=Karla:400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700" rel="stylesheet">

	<!-- Animate.css -->
	<link rel="stylesheet" href="~/css/animate.css">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="~/css/icomoon.css">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="~/css/bootstrap.css">
	<!-- Owl Carousel -->
	<link rel="stylesheet" href="~/css/owl.carousel.min.css">
	<link rel="stylesheet" href="~/css/owl.theme.default.min.css">
	<!-- Magnific Popup -->
	<link rel="stylesheet" href="~/css/magnific-popup.css">

	<link rel="stylesheet" href="~/css/style.css">


	<!-- Modernizr JS -->
	<script src="js/modernizr-2.6.2.min.js"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="js/respond.min.js"></script>
	<![endif]-->

</head>
<body>

	<nav id="colorlib-main-nav" role="navigation">
		<a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle active"><i></i></a>
		<div class="js-fullheight colorlib-table">
			<div class="colorlib-table-cell js-fullheight">
				<div class="row">
					<div class="col-md-12">
						<ul>
							<a href="@Url.Action("Login", "Account")"><i class="icon-user2"></i> Giriş Yap</a>
							<li class="active"><a href="@Url.Action("Index", "Home")">Ana Sayfa</a></li>
							<li><a href="services.html">Services</a></li>
							<li><a href="@Url.Action("Index", "Categories")">Kategoriler</a></li>
							<li><a href="@Url.Action("Index", "Library")">Kütüphane</a></li>
							<li><a href="@Url.Action("Index", "About")">Hakkında</a></li>
							<li><a href="@Url.Action("Index", "Contact")">İletişim</a></li>
						</ul>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<h2 class="head-title">Works</h2>
						<a href="~/images/work-1.jpg" class="gallery image-popup-link text-center" style="background-image: url(images/work-1.jpg);">
							<span><i class="icon-search3"></i></span>
						</a>
						<a href="~/images/work-2.jpg" class="gallery image-popup-link text-center" style="background-image: url(images/work-2.jpg);">
							<span><i class="icon-search3"></i></span>
						</a>
						<a href="~/images/work-3.jpg" class="gallery image-popup-link text-center" style="background-image: url(images/work-3.jpg);">
							<span><i class="icon-search3"></i></span>
						</a>
						<a href="~/images/work-4.jpg" class="gallery image-popup-link text-center" style="background-image: url(images/work-4.jpg);">
							<span><i class="icon-search3"></i></span>
						</a>
					</div>
				</div>
			</div>
		</div>
	</nav>

	<div id="colorlib-page">
		<header>
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="colorlib-navbar-brand">
							<a class="colorlib-logo" href="index.html"><span>Muhayyel</span>
						</div>
						<a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>
					</div>
				</div>
			</div>
		</header>

		<div id="colorlib-blog">
			<div class="container">
				<div class="row text-center">
					<h2 class="bold">Anı</h2>
				</div>
				<div class="row">
					<div class="col-md-12 col-md-offset-0 text-center animate-box intro-heading">
						<span>Blog</span>
						<h2>Read Our Case</h2>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<div class="rotate">
							<h2 class="heading">Our Blog</h2>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-4">
						<div class="article animate-box">
							<a href="blog.html" class="blog-img">
								<img class="img-responsive" src="~/images/img-1.jpg" alt="html5 bootstrap by colorlib.com">
								<div class="overlay"></div>
								<div class="link">
									<span class="read">Oku</h2>
								</div>
							</a>
							<div class="desc">
								<h2><a href="blog.html">A Japanese Constellation</a></h2>
								<p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove</p>
							</div>
						</div>

						<div class="article animate-box">
							<a href="blog.html" class="blog-img">
								<img class="img-responsive" src="~/images/img-4.jpg" alt="html5 bootstrap by colorlib.com">
								<div class="overlay"></div>
								<div class="link">
									<span class="read">Oku</h2>
								</div>
							</a>
							<div class="desc">
								<h2><a href="blog.html">A Japanese Constellation</a></h2>
								<p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove</p>
							</div>
						</div>

						<div class="article animate-box">
							<a href="blog.html" class="blog-img">
								<img class="img-responsive" src="~/images/img-7.jpg" alt="html5 bootstrap by colorlib.com">
								<div class="overlay"></div>
								<div class="link">
									<span class="read">Oku</h2>
								</div>
							</a>
							<div class="desc">
								<h2><a href="blog.html">A Japanese Constellation</a></h2>
								<p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove</p>
							</div>
						</div>
					</div>


					<div class="col-md-4">
						<div class="article animate-box">
							<a href="blog.html" class="blog-img">
								<img class="img-responsive" src="~/images/img-2.jpg" alt="html5 bootstrap by colorlib.com">
								<div class="overlay"></div>
								<div class="link">
									<span class="read">Oku</h2>
								</div>
							</a>
							<div class="desc">
								<h2><a href="blog.html">A Japanese Constellation</a></h2>
								<p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove</p>
							</div>
						</div>

						<div class="article animate-box">
							<a href="blog.html" class="blog-img">
								<img class="img-responsive" src="~/images/img-5.jpg" alt="html5 bootstrap by colorlib.com">
								<div class="overlay"></div>
								<div class="link">
									<span class="read">Oku</h2>
								</div>
							</a>
							<div class="desc">
								<h2><a href="blog.html">A Japanese Constellation</a></h2>
								<p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove</p>
							</div>
						</div>

						<div class="article animate-box">
							<a href="blog.html" class="blog-img">
								<img class="img-responsive" src="~/images/img-8.jpg" alt="html5 bootstrap by colorlib.com">
								<div class="overlay"></div>
								<div class="link">
									<span class="read">Oku</h2>
								</div>
							</a>
							<div class="desc">
								<h2><a href="blog.html">A Japanese Constellation</a></h2>
								<p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove</p>
							</div>
						</div>
					</div>


					<div class="col-md-4">
						<div class="article animate-box">
							<a href="blog.html" class="blog-img">
								<img class="img-responsive" src="~/images/img-3.jpg" alt="html5 bootstrap by colorlib.com">
								<div class="overlay"></div>
								<div class="link">
									<span class="read">Oku</h2>
								</div>
							</a>
							<div class="desc">
								<h2><a href="blog.html">A Japanese Constellation</a></h2>
								<p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove</p>
							</div>
						</div>

						<div class="article animate-box">
							<a href="blog.html" class="blog-img">
								<img class="img-responsive" src="~/images/img-6.jpg" alt="html5 bootstrap by colorlib.com">
								<div class="overlay"></div>
								<div class="link">
									<span class="read">Oku</h2>
								</div>
							</a>
							<div class="desc">
								<h2><a href="blog.html">A Japanese Constellation</a></h2>
								<p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove</p>
							</div>
						</div>

						<div class="article animate-box">
							<a href="blog.html" class="blog-img">
								<img class="img-responsive" src="~/images/img-9.jpg" alt="html5 bootstrap by colorlib.com">
								<div class="overlay"></div>
								<div class="link">
									<span class="read">Oku</h2>
								</div>
							</a>
							<div class="desc">
								<h2><a href="blog.html">A Japanese Constellation</a></h2>
								<p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>


		<footer>
			<div id="footer">
				<div class="container">
					<div class="row">
						<div class="col-md-4 col-pb-sm">
							<div class="row">
								<div class="col-md-10">
									<h2>Sosyal Medya</h2>
									<p>Yeniliklerden haberdar olmak için sosyal medya hesaplarımızı takip etmeyi unutmayın</p>
									<p>m.yasinbilgi03@gmail.com</p>
									<p class="colorlib-social-icons">
										<a href="https://github.com/YasinBilgi"><i class="icon-github"></i></a>
										<a href="https://www.instagram.com/m.yasinbilgi7/"><i class="icon-instagram"></i></a>
										<a href="https://twitter.com/myasinbilgi7"><i class="icon-twitter"></i></a>
										<a href="https://www.linkedin.com/in/muhammed-yasin-bilgi-266846249/"><i class="icon-linkedin"></i></a>
									</p>
								</div>
							</div>
						</div>
						<div class="col-md-4 col-pb-sm">
							<h2>Sayfalar</h2>
							<div class="f-entry">
								<a href="#" class="featured-img" style="background-image: url(images/img-1.jpg);"></a>
								<div class="desc">
									<h3><a href="@Url.Action("Index", "Home")">Ana Sayfa</a></h3>
								</div>
							</div>
							<div class="f-entry">
								<a href="#" class="featured-img" style="background-image: url(images/img-2.jpg);"></a>
								<div class="desc">
									<h3><a href="@Url.Action("Index","Categories")">Kategoriler</a></h3>
								</div>
							</div>
							<div class="f-entry">
								<a href="#" class="featured-img" style="background-image: url(images/img-3.jpg);"></a>
								<div class="desc">
									<h3><a href="@Url.Action("Index","About")">Hakkında</a></h3>
								</div>
							</div>
							<div class="f-entry">
								<a href="#" class="featured-img" style="background-image: url(images/img-3.jpg);"></a>
								<div class="desc">
									<h3><a href="@Url.Action("Index","Contact")">İletişim</a></h3>
								</div>
							</div>
						</div>
						<div class="col-md-4 col-pb-sm">
							<h2>Bildirim</h2>
							<p>Ayın kitaplarından ve yeni kitaplardan ilk sen haberdar olmak istiyorsan bizimle mail adresini paylaşman yeterli</p>
							<div class="subscribe text-center">
								<div class="form-group">
									<input type="text" class="form-control text-center" placeholder="E-Mail">
									<input type="submit" value="Paylaş" class="btn btn-primary btn-custom">
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</footer>

	</div>

	<!-- jQuery -->
	<script src="js/jquery.min.js"></script>
	<!-- jQuery Easing -->
	<script src="js/jquery.easing.1.3.js"></script>
	<!-- Bootstrap -->
	<script src="js/bootstrap.min.js"></script>
	<!-- Waypoints -->
	<script src="js/jquery.waypoints.min.js"></script>
	<!-- Owl Carousel -->
	<script src="js/owl.carousel.min.js"></script>
	<!-- Magnific Popup -->
	<script src="js/jquery.magnific-popup.min.js"></script>
	<script src="js/magnific-popup-options.js"></script>

	<!-- Main JS (Do not remove) -->
	<script src="js/main.js"></script>

</body>
</html>

EBookApp/EBookApp/Views/BookCategory/Roman.cshtml
@model EBook.Entities.Models.BookCategory
@{
    Layout = null;
}

<!DOCTYPE HTML>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Muhayyel-Roman</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="" />
	<meta name="keywords" content="" />
	<meta name="author" content="" />

	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content="" />
	<meta property="og:image" content="" />
	<meta property="og:url" content="" />
	<meta property="og:site_name" content="" />
	<meta property="og:description" content="" />
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="favicon.ico">

	<link href="https://fonts.googleapis.com/css?family=Karla:400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700" rel="stylesheet">

	<!-- Animate.css -->
	<link rel="stylesheet" href="~/css/animate.css">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="~/css/icomoon.css">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="~/css/bootstrap.css">
	<!-- Owl Carousel -->
	<link rel="stylesheet" href="~/css/owl.carousel.min.css">
	<link rel="stylesheet" href="~/css/owl.theme.default.min.css">
	<!-- Magnific Popup -->
	<link rel="stylesheet" href="~/css/magnific-popup.css">

	<link rel="stylesheet" href="~/css/style.css">


	<!-- Modernizr JS -->
	<script src="~/js/modernizr-2.6.2.min.js"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="~/js/respond.min.js"></script>
	<![endif]-->

</head>
<body>

	<nav id="colorlib-main-nav" role="navigation">
		<a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle active"><i></i></a>
		<div class="js-fullheight colorlib-table">
			<div class="colorlib-table-cell js-fullheight">
				<div class="row">
					<div class="col-md-12">
						<ul>
							<a href="@Url.Action("Login", "Account")"><i class="icon-user2"></i> Giriş Yap</a>
							<li class="active"><a href="@Url.Action("Index", "Home")">Ana Sayfa</a></li>
							<li><a href="services.html">Services</a></li>
							<li><a href="@Url.Action("Index", "Categories")">Kategoriler</a></li>
							<li><a href="@Url.Action("Index", "Library")">Kütüphane</a></li>
							<li><a href="@Url.Action("Index", "About")">Hakkında</a></li>
							<li><a href="@Url.Action("Index", "Contact")">İletişim</a></li>
						</ul>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<h2 class="head-title">Works</h2>
						<a href="~/images/work-1.jpg" class="gallery image-popup-link text-center" style="background-image: url(images/work-1.jpg);">
							<span><i class="icon-search3"></i></span>
						</a>
						<a href="~/images/work-2.jpg" class="gallery image-popup-link text-center" style="background-image: url(images/work-2.jpg);">
							<span><i class="icon-search3"></i></span>
						</a>
						<a href="~/images/work-3.jpg" class="gallery image-popup-link text-center" style="background-image: url(images/work-3.jpg);">
							<span><i class="icon-search3"></i></span>
						</a>
						<a href="~/images/work-4.jpg" class="gallery image-popup-link text-center" style="background-image: url(images/work-4.jpg);">
							<span><i class="icon-search3"></i></span>
						</a>
					</div>
				</div>
			</div>
		</div>
	</nav>

	<div id="colorlib-page">
		<header>
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="colorlib-navbar-brand">
							<a class="colorlib-logo" href="index.html"><span>Muhayyel</span>
						</div>
						<a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>
					</div>
				</div>
			</div>
		</header>

		<div id="colorlib-blog">
			<div class="container">
				<div class="row text-center">
					<h2 class="bold">Roman</h2>
				</div>
				<div class="row">
					<div class="col-md-12 col-md-offset-0 text-center animate-box intro-heading">
						<span>Blog</span>
						<h2>Read Our Case</h2>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<div class="rotate">
							<h2 class="heading">Our Blog</h2>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-4">
						<div class="article animate-box">
							<a href="@Url.Action("SavasVeBaris","Book")" class="blog-img">
								<img class="img-responsive" src="~/images/SavaşVeBarış.png" alt="html5 bootstrap by colorlib.com">
								<div class="overlay"></div>
								<div class="link">
									<span class="read">Oku</h2>
								</div>
							</a>
							<div class="desc">
								<h2><a href="blog.html">A Japanese Constellation</a></h2>
								<p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove</p>
							</div>
						</div>

						<div class="article animate-box">
							<a href="blog.html" class="blog-img">
								<img class="img-responsive" src="~/images/img-4.jpg" alt="html5 bootstrap by colorlib.com">
								<div class="overlay"></div>
								<div class="link">
									<span class="read">Oku</h2>
								</div>
							</a>
							<div class="desc">
								<h2><a href="blog.html">A Japanese Constellation</a></h2>
								<p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove</p>
							</div>
						</div>

						<div class="article animate-box">
							<a href="blog.html" class="blog-img">
								<img class="img-responsive" src="~/images/img-7.jpg" alt="html5 bootstrap by colorlib.com">
								<div class="overlay"></div>
								<div class="link">
									<span class="read">Oku</h2>
								</div>
							</a>
							<div class="desc">
								<h2><a href="blog.html">A Japanese Constellation</a></h2>
								<p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove</p>
							</div>
						</div>
					</div>


					<div class="col-md-4">
						<div class="article animate-box">
							<a href="blog.html" class="blog-img">
								<img class="img-responsive" src="~/images/img-2.jpg" alt="html5 bootstrap by colorlib.com">
								<div class="overlay"></div>
								<div class="link">
									<span class="read">Oku</h2>
								</div>
							</a>
							<div class="desc">
								<h2><a href="blog.html">A Japanese Constellation</a></h2>
								<p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove</p>
							</div>
						</div>

						<div class="article animate-box">
							<a href="blog.html" class="blog-img">
								<img class="img-responsive" src="~/images/img-5.jpg" alt="html5 bootstrap by colorlib.com">
								<div class="overlay"></div>
								<div class="link">
									<span class="read">Oku</h2>
								</div>
							</a>
							<div class="desc">
								<h2><a href="blog.html">A Japanese Constellation</a></h2>
								<p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove</p>
							</div>
						</div>

						<div class="article animate-box">
							<a href="blog.html" class="blog-img">
								<img class="img-responsive" src="~/images/img-8.jpg" alt="html5 bootstrap by colorlib.com">
								<div class="overlay"></div>
								<div class="link">
									<span class="read">Oku</h2>
								</div>
							</a>
							<div class="desc">
								<h2><a href="blog.html">A Japanese Constellation</a></h2>
								<p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove</p>
							</div>
						</div>
					</div>


					<div class="col-md-4">
						<div class="article animate-box">
							<a href="blog.html" class="blog-img">
								<img class="img-responsive" src="~/images/img-3.jpg" alt="html5 bootstrap by colorlib.com">
								<div class="overlay"></div>
								<div class="link">
									<span class="read">Oku</h2>
								</div>
							</a>
							<div class="desc">
								<h2><a href="blog.html">A Japanese Constellation</a></h2>
								<p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove</p>
							</div>
						</div>

						<div class="article animate-box">
							<a href="blog.html" class="blog-img">
								<img class="img-responsive" src="~/images/img-6.jpg" alt="html5 bootstrap by colorlib.com">
								<div class="overlay"></div>
								<div class="link">
									<span class="read">Oku</h2>
								</div>
							</a>
							<div class="desc">
								<h2><a href="blog.html">A Japanese Constellation</a></h2>
								<p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove</p>
							</div>
						</div>

						<div class="article animate-box">
							<a href="blog.html" class="blog-img">
								<img class="img-responsive" src="~/images/img-9.jpg" alt="html5 bootstrap by colorlib.com">
								<div class="overlay"></div>
								<div class="link">
									<span class="read">Oku</h2>
								</div>
							</a>
							<div class="desc">
								<h2><a href="blog.html">A Japanese Constellation</a></h2>
								<p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>


		<footer>
			<div id="footer">
				<div class="container">
					<div class="row">
						<div class="col-md-4 col-pb-sm">
							<div class="row">
								<div class="col-md-10">
									<h2>Sosyal Medya</h2>
									<p>Yeniliklerden haberdar olmak için sosyal medya hesaplarımızı takip etmeyi unutmayın</p>
									<p>m.yasinbilgi03@gmail.com</p>
									<p class="colorlib-social-icons">
										<a href="https://github.com/YasinBilgi"><i class="icon-github"></i></a>
										<a href="https://www.instagram.com/m.yasinbilgi7/"><i class="icon-instagram"></i></a>
										<a href="https://twitter.com/myasinbilgi7"><i class="icon-twitter"></i></a>
										<a href="https://www.linkedin.com/in/muhammed-yasin-bilgi-266846249/"><i class="icon-linkedin"></i></a>
									</p>
								</div>
							</div>
						</div>
						<div class="col-md-4 col-pb-sm">
							<h2>Sayfalar</h2>
							<div class="f-entry">
								<a href="#" class="featured-img" style="background-image: url(images/img-1.jpg);"></a>
								<div class="desc">
									<h3><a href="@Url.Action("Index", "Home")">Ana Sayfa</a></h3>
								</div>
							</div>
							<div class="f-entry">
								<a href="#" class="featured-img" style="background-image: url(images/img-2.jpg);"></a>
								<div class="desc">
									<h3><a href="@Url.Action("Index","Categories")">Kategoriler</a></h3>
								</div>
							</div>
							<div class="f-entry">
								<a href="#" class="featured-img" style="background-image: url(images/img-3.jpg);"></a>
								<div class="desc">
									<h3><a href="@Url.Action("Index","About")">Hakkında</a></h3>
								</div>
							</div>
							<div class="f-entry">
								<a href="#" class="featured-img" style="background-image: url(images/img-3.jpg);"></a>
								<div class="desc">
									<h3><a href="@Url.Action("Index","Contact")">İletişim</a></h3>
								</div>
							</div>
						</div>
						<div class="col-md-4 col-pb-sm">
							<h2>Bildirim</h2>
							<p>Ayın kitaplarından ve yeni kitaplardan ilk sen haberdar olmak istiyorsan bizimle mail adresini paylaşman yeterli</p>
							<div class="subscribe text-center">
								<div class="form-group">
									<input type="text" class="form-control text-center" placeholder="E-Mail">
									<input type="submit" value="Paylaş" class="btn btn-primary btn-custom">
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</footer>

	</div>

	<!-- jQuery -->
	<script src="~/js/jquery.min.js"></script>
	<!-- jQuery Easing -->
	<script src="~/js/jquery.easing.1.3.js"></script>
	<!-- Bootstrap -->
	<script src="~/js/bootstrap.min.js"></script>
	<!-- Waypoints -->
	<script src="~/js/jquery.waypoints.min.js"></script>
	<!-- Owl Carousel -->
	<script src="~/js/owl.carousel.min.js"></script>
	<!-- Magnific Popup -->
	<script src="~/js/jquery.magnific-popup.min.js"></script>
	<script src="~/js/magnific-popup-options.js"></script>

	<!-- Main JS (Do not remove) -->
	<script src="~/js/main.js"></script>

</body>
</html>