EBookApp/EBookApp/Areas/ManagementPanel/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EBook.Entities.Models;
using EBookApp.Areas.ManagementPanel.Helpers;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace EBookApp.Areas.ManagementPanel.Controllers
{
    [Area("ManagementPanel")]
    public class BooksController : Controller
    {
        private readonly EBookDbContext context = new EBookDbContext();

        private readonly IWebHostEnvironment _hostEnvironment;

        public BooksController(IWebHostEnvironment hostEnvironment)
        {
            _hostEnvironment = hostEnvironment;
        }

        // GET: ManagementPanel/Books
        public async Task<IActionResult> Index()
        {
            var eBookDbContext = context.Books.Include(b => b.Library).Include(b => b.User);
            return View(await eBookDbContext.ToListAsync());
        }

        // GET: ManagementPanel/Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || context.Books == null)
            {
                return NotFound();
            }

            var book = await context.Books
                .Include(b => b.Library)
                .Include(b => b.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: ManagementPanel/Books/Create
        public IActionResult Create()
        {
            ViewData["LibraryId"] = new SelectList(context.Libraries, "Id", "LibraryName");
            ViewData["UserId"] = new SelectList(context.Users, "Id", "Email");
            return View();
        }

        // POST: ManagementPanel/Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Book book, IFormFile img)
        {
            if (ModelState.IsValid)
            {
                if (img != null)
                {
                    book.İmageUrl = await İmageUpload.UploadImageAsync(_hostEnvironment, img);
                }
                book.Status = true;
                book.CreatedDate = DateTime.Now;

                context.Books.Add(book);
                await context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["LibraryId"] = new SelectList(context.Libraries, "Id", "LibraryName", book.LibraryId);
            ViewData["UserId"] = new SelectList(context.Users, "Id", "Email", book.UserId);
            return View(book);
        }

        // GET: ManagementPanel/Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || context.Books == null)
            {
                return NotFound();
            }

            var book = await context.Books.Include(x => x.BookDetail).FirstOrDefaultAsync(r => r.Id == id);
            if (book == null)
            {
                return NotFound();
            }
            ViewData["LibraryId"] = new SelectList(context.Libraries, "Id", "LibraryName", book.LibraryId);
            ViewData["UserId"] = new SelectList(context.Users, "Id", "Email", book.UserId);
            return View(book);
        }

        // POST: ManagementPanel/Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Book book, IFormFile img)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Book editBook = await context.Books.Include(x => x.BookDetail).FirstOrDefaultAsync(r => r.Id == book.Id);
                    if (img != null)
                    {
                        editBook.İmageUrl = await İmageUpload.UploadImageAsync(_hostEnvironment, img);
                    }

                    editBook.Name = book.Name;
                    editBook.AuthorName = book.AuthorName;
                    editBook.NumberPage = book.NumberPage;
                    editBook.PublishDate = book.PublishDate;
                    editBook.Isbn = book.Isbn;
                    editBook.Status = book.Status;
                    editBook.Description = book.Description;

                    await context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {

                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LibraryId"] = new SelectList(context.Libraries, "Id", "LibraryName", book.LibraryId);
            ViewData["UserId"] = new SelectList(context.Users, "Id", "Email", book.UserId);
            return View(book);
        }

        // GET: ManagementPanel/Books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || context.Books == null)
            {
                return NotFound();
            }

            var book = await context.Books
                .Include(b => b.Library)
                .Include(b => b.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: ManagementPanel/Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (context.Books == null)
            {
                return Problem("Entity set 'EBookDbContext.Books'  is null.");
            }
            var book = await context.Books.FindAsync(id);
            if (book != null)
            {
                context.Books.Remove(book);
            }
            
            await context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(int id)
        {
          return (context.Books?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

EBookApp/EBookApp/Areas/ManagementPanel/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EBook.Entities.Models;

namespace EBookApp.Areas.ManagementPanel.Controllers
{
    [Area("ManagementPanel")]
    public class CategoriesController : Controller
    {
        private readonly EBookDbContext _context = new EBookDbContext();

        // GET: ManagementPanel/Categories
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categories.ToListAsync());
        }

        // GET: ManagementPanel/Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: ManagementPanel/Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ManagementPanel/Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Category category)
        {
            if (ModelState.IsValid)
            {
                category.Status = true;
                category.CreatedDate = DateTime.Now;

                _context.Categories.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: ManagementPanel/Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: ManagementPanel/Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Category editCategory = await _context.Categories.FindAsync(category.Id);

                    editCategory.Name = category.Name;
                    editCategory.Status = category.Status;

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                  
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: ManagementPanel/Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: ManagementPanel/Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Categories == null)
            {
                return Problem("Entity set 'EBookDbContext.Categories'  is null.");
            }
            var category = await _context.Categories.FindAsync(id);
            if (category != null)
            {
                _context.Categories.Remove(category);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
          return (_context.Categories?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

EBookApp/EBookApp/Controllers/CategoriesController.cs
using EBook.Entities.Models;
using Microsoft.AspNetCore.Mvc;

namespace EBookApp.Controllers
{
	public class CategoriesController : Controller
	{
        EBookDbContext context = new EBookDbContext();

        public IActionResult Index()
		{
            return View();
		}
	}
}

EBookApp/EBookApp/Areas/ManagementPanel/Views/Categories/Create.cshtml
@model EBook.Entities.Models.Category

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/ManagementPanel/Views/Shared/_Layout.cshtml";
}

<h1>Kategori Ekle</h1>

@using (Html.BeginForm("Create", "Categories", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new {@class="text-danger"})

        <label class="control-label col-md-2">Kategori Adı</label>
        <div class="form-group">
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new {htmlAttibutes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Name, "", new {@Classs = "text-danger"})
            </div>
        </div>

        <label class="control-label col-md-2">Ekleme Tarihi</label>
        <div class="form-group">
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDate, new {htmlAttibutes = new {@class = "form-control", @type="datetime"}})
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new {@Classs = "text-danger"})
            </div>
        </div>

        <br />
        <input type="submit" value="Kaydet" class="btn btn-primary" />
        <br />
    </div>
}

EBookApp/EBookApp/Areas/ManagementPanel/Views/Categories/Delete.cshtml
@model EBook.Entities.Models.Category

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/ManagementPanel/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

EBookApp/EBookApp/Areas/ManagementPanel/Views/Categories/Details.cshtml
@model EBook.Entities.Models.Category

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/ManagementPanel/Views/Shared/_Layout.cshtml";
}

<h1>Detay</h1>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Favori Adı
        </dt>
        <dd class = "col-sm-10">
            @Model.Name
        </dd>
        <dt class = "col-sm-2">
            Durum
        </dt>
        <dd class = "col-sm-10">
            @Model.Status
        </dd>
        <dt class = "col-sm-2">
            Ekleme Tarihi
        </dt>
        <dd class = "col-sm-10">
            @Model.CreatedDate
        </dd>
    </dl>
</div>

EBookApp/EBookApp/Areas/ManagementPanel/Views/Categories/Edit.cshtml
@model EBook.Entities.Models.Category

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/ManagementPanel/Views/Shared/_Layout.cshtml";
}

<h1>Düzenle</h1>

@using (Html.BeginForm("Edit", "Categories", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new {@class="text-danger"})
        @Html.HiddenFor(model => model.Id)

        <label class="control-label col-md-2">Favori Adı</label>
        <div class="form-group">
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new {htmlAttibutes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Name, "", new {@Classs = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new {@class = "control-label col-md-2"})

            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Status, new SelectList(
            new[]{
            new{Value = "true", Text = "Aktif"},
            new{Value = "false", Text = "Pasif"}
            },
            "Value",
            "Text",
            Model.Status), new{@class = "form-control"})
            </div>
            @Html.ValidationMessageFor(model => model.Status, "",
        new {@class = "text-danger"})
        </div>

        <br />
        <input type="submit" value="Kaydet" class="btn btn-primary" />
    </div>
}

EBookApp/EBookApp/Areas/ManagementPanel/Views/Categories/Index.cshtml
@model IEnumerable<EBook.Entities.Models.Category>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/ManagementPanel/Views/Shared/_Layout.cshtml";
}

<h1>Kategoriler</h1>

<p>
    <a class="btn btn-primary" href="@Url.Action("Create", "Categories")">Ekle</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Durum
            </th>
            <th>
                Ekleme Tarihi
            </th>
            <th>
                Detay
            </th>
            <th>
                Düzenle
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @item.Name
            </td>
                <td>
                    @if (item.Status == true)
                    {
                        <p>Aktif</p>
                    }
                    else
                    {
                        <p>Pasif</p>
                    }
                </td>
                <td>
                    @item.CreatedDate.ToString("dd MMMM yyyy HH:mm")
                </td>
                <td>
                    <a class="btn btn-danger" href="@Url.Action("Details", "Books", new{id = item.Id})">Detay</a>
                </td>

                <td>
                    <a class="btn btn-warning" href="@Url.Action("Edit", "Books", new{id = item.Id})">Düzenle</a>
                </td>
        </tr>
}
    </tbody>
</table>