EBookApp/EBookApp/Areas/ManagementPanel/Controllers/LibrariesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EBook.Entities.Models;

namespace EBookApp.Areas.ManagementPanel.Controllers
{
    [Area("ManagementPanel")]
    public class LibrariesController : Controller
    {
        private readonly EBookDbContext _context = new EBookDbContext();

        
        // GET: ManagementPanel/Libraries
        public async Task<IActionResult> Index()
        {
            var eBookDbContext = _context.Libraries.Include(l => l.User);
            return View(await eBookDbContext.ToListAsync());
        }

        // GET: ManagementPanel/Libraries/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Libraries == null)
            {
                return NotFound();
            }

            var library = await _context.Libraries
                .Include(l => l.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (library == null)
            {
                return NotFound();
            }

            return View(library);
        }

        // GET: ManagementPanel/Libraries/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Email");
            return View();
        }

        // POST: ManagementPanel/Libraries/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Library library)
        {
            if (ModelState.IsValid)
            {
                library.Status = true;
                library.CreatedDate = DateTime.Now;

                _context.Libraries.Add(library);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Email", library.UserId);
            return View(library);
        }

        // GET: ManagementPanel/Libraries/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Libraries == null)
            {
                return NotFound();
            }

            var library = await _context.Libraries.FindAsync(id);
            if (library == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Email", library.UserId);
            return View(library);
        }

        // POST: ManagementPanel/Libraries/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Library library)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Library editLibrary = await _context.Libraries.FirstOrDefaultAsync(r => r.Id == library.Id);

                    editLibrary.LibraryName = library.LibraryName;
                    editLibrary.Status = library.Status;

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {

                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Email", library.UserId);
            return View(library);
        }

        // GET: ManagementPanel/Libraries/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Libraries == null)
            {
                return NotFound();
            }

            var library = await _context.Libraries
                .Include(l => l.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (library == null)
            {
                return NotFound();
            }

            return View(library);
        }

        // POST: ManagementPanel/Libraries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Libraries == null)
            {
                return Problem("Entity set 'EBookDbContext.Libraries'  is null.");
            }
            var library = await _context.Libraries.FindAsync(id);
            if (library != null)
            {
                _context.Libraries.Remove(library);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LibraryExists(int id)
        {
          return (_context.Libraries?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

EBookApp/EBookApp/Controllers/LibraryController.cs
using EBook.Entities.Models;
using Microsoft.AspNetCore.Mvc;

namespace EBookApp.Controllers
{
    public class LibraryController : Controller
    {
        EBookDbContext context = new EBookDbContext();

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]

        public async Task<IActionResult> Index(Library library)
        {
            return View();
        }
    }
}

EBookApp/EBookApp/Areas/ManagementPanel/Views/Libraries/Create.cshtml
@model EBook.Entities.Models.Library

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/ManagementPanel/Views/Shared/_Layout.cshtml";
}

<h1>Kütüphane Ekle</h1>

@using (Html.BeginForm("Create", "Libraries", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new {@class="text-danger"})

        <label class="control-label col-md-2">Kütüphane Adı</label>
        <div class="form-group">
            <div class="col-md-10">
                @Html.EditorFor(model => model.LibraryName, new {htmlAttibutes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.LibraryName, "", new {@Classs = "text-danger"})
            </div>
        </div>

        <label class="control-label col-md-2">Ekleme Tarihi</label>
        <div class="form-group">
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDate, new {htmlAttibutes = new {@class = "form-control", @type="datetime"}})
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new {@Classs = "text-danger"})
            </div>
        </div>

        <br />
        <input type="submit" value="Kaydet" class="btn btn-primary" />
        <br />
    </div>
}

EBookApp/EBookApp/Areas/ManagementPanel/Views/Libraries/Delete.cshtml
@model EBook.Entities.Models.Library

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/ManagementPanel/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Library</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LibraryName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LibraryName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Email)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

EBookApp/EBookApp/Areas/ManagementPanel/Views/Libraries/Details.cshtml
@model EBook.Entities.Models.Library

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/ManagementPanel/Views/Shared/_Layout.cshtml";
}

<h1>Detay</h1>

<div>
    <h4>Library</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Kütüphane Adı
        </dt>
        <dd class = "col-sm-10">
            @Model.LibraryName
        </dd>
        <dt class = "col-sm-2">
            Durum
        </dt>
        <dd class = "col-sm-10">
            @Model.Status
        </dd>
        <dt class = "col-sm-2">
           Ekleme Tarihi
        </dt>
        <dd class = "col-sm-10">
            @Model.CreatedDate
        </dd>
    </dl>
</div>

EBookApp/EBookApp/Areas/ManagementPanel/Views/Libraries/Edit.cshtml
@model EBook.Entities.Models.Library

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/ManagementPanel/Views/Shared/_Layout.cshtml";
}

<h1>Düzenle</h1>

@using (Html.BeginForm("Edit", "Libraries", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new {@class="text-danger"})
        @Html.HiddenFor(model => model.Id)

        <label class="control-label col-md-2">Kitap Adı</label>
        <div class="form-group">
            <div class="col-md-10">
                @Html.EditorFor(model => model.LibraryName, new {htmlAttibutes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.LibraryName, "", new {@Classs = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new {@class = "control-label col-md-2"})

            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Status, new SelectList(
            new[]{
            new{Value = "true", Text = "Aktif"},
            new{Value = "false", Text = "Pasif"}
            },
            "Value",
            "Text",
            Model.Status), new{@class = "form-control"})
            </div>
            @Html.ValidationMessageFor(model => model.Status, "",
        new {@class = "text-danger"})
        </div>

        <br />
        <input type="submit" value="Kaydet" class="btn btn-primary" />
    </div>
}

EBookApp/EBookApp/Areas/ManagementPanel/Views/Libraries/Index.cshtml
@model IEnumerable<EBook.Entities.Models.Library>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/ManagementPanel/Views/Shared/_Layout.cshtml";
}

<h1>Kütüphane</h1>

<p>
<p>
    <a class="btn btn-primary" href="@Url.Action("Create", "Libraries")">Ekle</a>
</p>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Kütüphane Adı
            </th>
            <th>
                Durum
            </th>
            <th>
                Ekleme tarihi
            </th>
            <th>
                Detay
            </th>
            <th>
                Düzenle
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
                <td>
                    @item.LibraryName
                </td>
                <td>
                    @if (item.Status == true)
                    {
                        <p>Aktif</p>
                    }
                    else
                    {
                        <p>Pasif</p>
                    }
                </td>
                <td>
                    @item.CreatedDate.ToString("dd MMMM yyyy HH:mm")
                </td>
                <td>
                    <a class="btn btn-danger" href="@Url.Action("Details", "Libraries", new{id = item.Id})">Detay</a>
                </td>

                <td>
                    <a class="btn btn-warning" href="@Url.Action("Edit", "Libraries", new{id = item.Id})">Düzenle</a>
                </td>
        </tr>
}
    </tbody>
</table>