EBookApp/EBookApp/Areas/ManagementPanel/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EBook.Entities.Models;

namespace EBookApp.Areas.ManagementPanel.Controllers
{
    [Area("ManagementPanel")]
    public class CategoriesController : Controller
    {
        private readonly EBookDbContext _context = new EBookDbContext();

        // GET: ManagementPanel/Categories
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categories.ToListAsync());
        }

        // GET: ManagementPanel/Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: ManagementPanel/Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ManagementPanel/Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Category category)
        {
            if (ModelState.IsValid)
            {
                category.Status = true;
                category.CreatedDate = DateTime.Now;

                _context.Categories.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: ManagementPanel/Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: ManagementPanel/Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Category editCategory = await _context.Categories.FindAsync(category.Id);

                    editCategory.Name = category.Name;
                    editCategory.Status = category.Status;

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                  
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: ManagementPanel/Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: ManagementPanel/Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Categories == null)
            {
                return Problem("Entity set 'EBookDbContext.Categories'  is null.");
            }
            var category = await _context.Categories.FindAsync(id);
            if (category != null)
            {
                _context.Categories.Remove(category);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
          return (_context.Categories?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

EBookApp/EBookApp/Controllers/AboutController.cs
using EBook.Entities.Models;
using Microsoft.AspNetCore.Mvc;

namespace EBookApp.Controllers
{
    public class AboutController : Controller
    {
        EBookDbContext context = new EBookDbContext();

        public IActionResult Index()
        {
            return View();
        }
    }
}

EBookApp/EBookApp/Controllers/BookCategoryController.cs
using Microsoft.AspNetCore.Mvc;

namespace EBookApp.Controllers
{
	public class BookCategoryController : Controller
	{
        public IActionResult Roman()
        {
            return View();
        }

        public IActionResult Tarih()
        {
            return View();
        }

        public IActionResult BilimKurgu()
        {
            return View();
        }

        public IActionResult KisiselGelisim()
        {
            return View();
        }

        public IActionResult CizgiRoman()
        {
            return View();
        }

        public IActionResult Hikaye()
        {
            return View();
        }

        public IActionResult Ani()
        {
            return View();
        }
    }
}

EBookApp/EBookApp/Controllers/CategoriesController.cs
using EBook.Entities.Models;
using Microsoft.AspNetCore.Mvc;

namespace EBookApp.Controllers
{
	public class CategoriesController : Controller
	{
        EBookDbContext context = new EBookDbContext();

        public IActionResult Index()
		{
            return View();
		}
	}
}

EBookApp/EBookApp/Controllers/ContactController.cs
using EBook.Entities.Models;
using Microsoft.AspNetCore.Mvc;

namespace EBookApp.Controllers
{
    public class ContactController : Controller
    {
        EBookDbContext context = new EBookDbContext();

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(Contact contact)
        {
            if(User == null)
            {
              
            }
            return View(contact);
        }
    }
}

EBookApp/EBookApp/Controllers/LibraryController.cs
using EBook.Entities.Models;
using Microsoft.AspNetCore.Mvc;

namespace EBookApp.Controllers
{
    public class LibraryController : Controller
    {
        EBookDbContext context = new EBookDbContext();

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]

        public async Task<IActionResult> Index(Library library)
        {
            return View();
        }
    }
}

EBookApp/EBookApp/Views/Categories/Index.cshtml
@model EBook.Entities.Models.Category
@{
	Layout = null;
}

<!DOCTYPE HTML>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Noah Template</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="" />
	<meta name="keywords" content="" />
	<meta name="author" content="" />

	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content="" />
	<meta property="og:image" content="" />
	<meta property="og:url" content="" />
	<meta property="og:site_name" content="" />
	<meta property="og:description" content="" />
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="favicon.ico">

	<link href="https://fonts.googleapis.com/css?family=Karla:400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700" rel="stylesheet">

	<!-- Animate.css -->
	<link rel="stylesheet" href="css/animate.css">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="css/icomoon.css">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="css/bootstrap.css">
	<!-- Owl Carousel -->
	<link rel="stylesheet" href="css/owl.carousel.min.css">
	<link rel="stylesheet" href="css/owl.theme.default.min.css">
	<!-- Magnific Popup -->
	<link rel="stylesheet" href="css/magnific-popup.css">

	<link rel="stylesheet" href="css/style.css">


	<!-- Modernizr JS -->
	<script src="js/modernizr-2.6.2.min.js"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="js/respond.min.js"></script>
	<![endif]-->

</head>
<body>

	<nav id="colorlib-main-nav" role="navigation">
		<a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle active"><i></i></a>
		<div class="js-fullheight colorlib-table">
			<div class="colorlib-table-cell js-fullheight">
				<div class="row">
					<div class="col-md-12">
						<ul>
							<a href="@Url.Action("Login", "Account")"><i class="icon-user2"></i> Giriş Yap</a>
							<li class="active"><a href="@Url.Action("Index", "Home")">Ana Sayfa</a></li>
							<li><a href="services.html">Services</a></li>
							<li><a href="@Url.Action("Index", "Categories")">Kategoriler</a></li>
							<li><a href="@Url.Action("Index", "Library")">Kütüphane</a></li>
							<li><a href="@Url.Action("Index", "About")">Hakkında</a></li>
							<li><a href="@Url.Action("Index", "Contact")">İletişim</a></li>
						</ul>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<h2 class="head-title">Works</h2>
						<a href="images/work-1.jpg" class="gallery image-popup-link text-center" style="background-image: url(images/work-1.jpg);">
							<span><i class="icon-search3"></i></span>
						</a>
						<a href="images/work-2.jpg" class="gallery image-popup-link text-center" style="background-image: url(images/work-2.jpg);">
							<span><i class="icon-search3"></i></span>
						</a>
						<a href="images/work-3.jpg" class="gallery image-popup-link text-center" style="background-image: url(images/work-3.jpg);">
							<span><i class="icon-search3"></i></span>
						</a>
						<a href="images/work-4.jpg" class="gallery image-popup-link text-center" style="background-image: url(images/work-4.jpg);">
							<span><i class="icon-search3"></i></span>
						</a>
					</div>
				</div>
			</div>
		</div>
	</nav>

	<div id="colorlib-page">
		<header>
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="colorlib-navbar-brand">
							<a class="colorlib-logo" href="@Url.Action("Index", "Home")"><span>Muhayyel</span></a>
						</div>
						<a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>
					</div>
				</div>
			</div>
		</header>
		<div id="colorlib-work">
			<div class="container">
				<div class="row text-center">
					<h2 class="bold">Kategoriler</h2>
				</div>
				<div class="row">
					<div class="col-md-12 col-md-offset-0 text-center animate-box intro-heading">
						<span>İstediğin Kitaplara Erişmek Artık Çok Kolay</span>
						<h2>Keşfetmeye Başla</h2>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<div class="rotate">
							<h2 class="heading">Kategoriler</h2>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<div class="work-entry animate-box">
							<a href="@Url.Action("Roman","BookCategory")" class="work-img" style="background-image: url(images/work-1.jpg);">
								<div class="display-t">
									<div class="work-name">
										<h2>Roman</h2>
									</div>
								</div>
							</a>
							<div class="col-md-4 col-md-offset-4">
								<div class="desc">
									<p>Roman, genellikle kurgusal bir hikayeyi anlatan uzun bir edebi türdür. Karakter gelişimi, olay örgüsü ve genellikle duygusal bir tema içerir. Romanlar genellikle çeşitli alt türleri içerebilir, örneğin bilim kurgu romanları, polisiye romanlar, aşk romanları vb.</p>
									<p class="read"><a href="@Url.Action("Roman","BookCategory")">Keşfet</a></p>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-12">
						<div class="work-entry animate-box">
							<a href="@Url.Action("Tarih","BookCategory")" class="work-img" style="background-image: url(images/work-2.jpg);">
								<div class="display-t">
									<div class="work-name">
										<h2>Tarih</h2>
									</div>
								</div>
							</a>
							<div class="col-md-4 col-md-offset-4">
								<div class="desc">
									<p>Tarih, geçmişteki olayları, toplumları, kültürleri ve insanlığın gelişimini inceleyen bir disiplindir. Ancak, tarih sadece bilimsel bir alan olmanın ötesinde, aynı zamanda edebi eserlerin ve romanların da ana kaynaklarından biridir. Tarihsel metinler genellikle belgeler, araştırmalar ve arkeolojik bulgular temelinde yazılır, ancak tarihî romanlar gibi kurgusal eserler de tarihi olayları veya dönemleri anlatarak geçmişi canlandırabilir.</p>
									<p class="read"><a href="@Url.Action("Tarih","BookCategory")">Keşfet</a></p>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-12">
						<div class="work-entry animate-box">
							<a href="@Url.Action("BilimKurgu","BookCategory")" class="work-img" style="background-image: url(images/work-3.jpg);">
								<div class="display-t">
									<div class="work-name">
										<h2>Bilim Kurgu</h2>
									</div>
								</div>
							</a>
							<div class="col-md-4 col-md-offset-4">
								<div class="desc">
									<p>Bilim kurgu, bilim ve teknolojinin ileri seviyede kullanılması veya henüz gerçekleşmemiş olayların ve teknolojik gelişmelerin konu edildiği bir edebi türdür. Bu tür, genellikle gelecekteki bir zamanı, uzayı, farklı boyutları veya alternatif gerçeklikleri konu alır. Bilim kurgu eserleri, yazarların hayal gücüne dayanarak bilimsel prensipleri ve teknolojik ilerlemeleri kullanır.</p>
									<p class="read"><a href="@Url.Action("BilimKurgu","BookCategory")">Keşfet</a></p>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-12">
						<div class="work-entry animate-box">
							<a href="@Url.Action("KisiselGelisim","BookCategory")" class="work-img" style="background-image: url(images/work-4.jpg);">
								<div class="display-t">
									<div class="work-name">
										<h2>Kişisel Gelişim</h2>
									</div>
								</div>
							</a>
							<div class="col-md-4 col-md-offset-4">
								<div class="desc">
									<p>Kişisel gelişim, bireylerin potansiyellerini maksimum seviyeye çıkarmaya yönelik bir süreç ve çaba olarak tanımlanabilir. Bu alan, bireylerin kendilerini daha iyi anlamalarını, hedeflerine odaklanmalarını, yeteneklerini geliştirmelerini ve yaşam kalitelerini artırmalarını amaçlar. Kişisel gelişim, genellikle bireyin zihinsel, duygusal, sosyal ve fiziksel alanlarda kendini geliştirmesini içerir.</p>
									<p class="read"><a href="@Url.Action("KisiselGelisim","BookCategory")">Keşfet</a></p>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-12">
						<div class="work-entry animate-box">
							<a href="@Url.Action("CizgiRoman","BookCategory")" class="work-img" style="background-image: url(images/work-5.jpg);">
								<div class="display-t">
									<div class="work-name">
										<h2>Çizgi Roman</h2>
									</div>
								</div>
							</a>
							<div class="col-md-4 col-md-offset-4">
								<div class="desc">
									<p>Resimli roman olarak da adlandırılan çizgi roman; bir öyküyü anlatmak için görsellerden ve çizgilerden yararlanılan bir tür olarak tanımlanır. Çizgi romanlarda anlatı, çizimler üzerinden gerçekleştirilir. Diyaloglar ise konuşma balonları içerisinde yer alır.</p>
									<p class="read"><a href="@Url.Action("CizgiRoman","BookCategory")">Keşfet</a></p>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-12">
						<div class="work-entry animate-box">
							<a href="@Url.Action("Hikaye","BookCategory")" class="work-img" style="background-image: url(images/work-6.jpg);">
								<div class="display-t">
									<div class="work-name">
										<h2>Hikaye</h2>
									</div>
								</div>
							</a>
							<div class="col-md-4 col-md-offset-4">
								<div class="desc">
									<p>Hikaye ya da öykü, gerçek ve gerçeğe yakın bir olayı aktaran kısa, düzyazı şeklindeki anlatıdır. Kısa oluşu, yalın bir olay örgüsüne sahip olması, genellikle önemli bir olay ya da sahne aracılığıyla tek ve yoğun bir etki uyandırması ve az sayıda karaktere yer vermesiyle roman ve diğer anlatı türlerinden ayrılır.</p>
									<p class="read"><a href="@Url.Action("Hikaye","BookCategory")">Keşfet</a></p>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-12">
						<div class="work-entry animate-box">
							<a href="@Url.Action("Ani","BookCategory")" class="work-img" style="background-image: url(images/work-7.jpg);">
								<div class="display-t">
									<div class="work-name">
										<h2>Anı</h2>
									</div>
								</div>
							</a>
							<div class="col-md-4 col-md-offset-4">
								<div class="desc">
									<p>Anı, edebiyatta kişisel yaşantının bütününü veya belli bölümlerini kapsayan, bu dönemlerdeki gözlemleri dile getirmek amacıyla yazılmış metinlerdir. Otobiyografi ile karıştırılabilen anı, ondan dışsal olaylara verdiği önem ile ayrılır.</p>
									<p class="read"><a href="@Url.Action("Ani","BookCategory")">Keşfet</a></p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<footer>
			<div id="footer">
				<div class="container">
					<div class="row">
						<div class="col-md-4 col-pb-sm">
							<div class="row">
								<div class="col-md-10">
									<h2>Sosyal Medya</h2>
									<p>Yeniliklerden haberdar olmak için sosyal medya hesaplarımızı takip etmeyi unutmayın</p>
									<p>m.yasinbilgi03@gmail.com</p>
									<p class="colorlib-social-icons">
										<a href="https://github.com/YasinBilgi"><i class="icon-github"></i></a>
										<a href="https://www.instagram.com/m.yasinbilgi7/"><i class="icon-instagram"></i></a>
										<a href="https://twitter.com/myasinbilgi7"><i class="icon-twitter"></i></a>
										<a href="https://www.linkedin.com/in/muhammed-yasin-bilgi-266846249/"><i class="icon-linkedin"></i></a>
									</p>
								</div>
							</div>
						</div>
						<div class="col-md-4 col-pb-sm">
							<h2>Sayfalar</h2>
							<div class="f-entry">
								<a href="#" class="featured-img" style="background-image: url(images/img-1.jpg);"></a>
								<div class="desc">
									<h3><a href="@Url.Action("Index","Home")">Ana Sayfa</a></h3>
								</div>
							</div>
							<div class="f-entry">
								<a href="#" class="featured-img" style="background-image: url(images/img-2.jpg);"></a>
								<div class="desc">
									<h3><a href="@Url.Action("Index","Categories")">Kategoriler</a></h3>
								</div>
							</div>
							<div class="f-entry">
								<a href="#" class="featured-img" style="background-image: url(images/img-3.jpg);"></a>
								<div class="desc">
									<h3><a href="@Url.Action("Index","About")">Hakkında</a></h3>
								</div>
							</div>
							<div class="f-entry">
								<a href="#" class="featured-img" style="background-image: url(images/img-3.jpg);"></a>
								<div class="desc">
									<h3><a href="@Url.Action("Index","Contact")">İletişim</a></h3>
								</div>
							</div>
						</div>
						<div class="col-md-4 col-pb-sm">
							<h2>Bildirim</h2>
							<p>Ayın kitaplarından ve yeni kitaplardan ilk sen haberdar olmak istiyorsan bizimle mail adresini paylaşman yeterli</p>
							<div class="subscribe text-center">
								<div class="form-group">
									<input type="text" class="form-control text-center" placeholder="E-Mail">
									<input type="submit" value="Paylaş" class="btn btn-primary btn-custom">
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</footer>

	</div>

	<!-- jQuery -->
	<script src="js/jquery.min.js"></script>
	<!-- jQuery Easing -->
	<script src="js/jquery.easing.1.3.js"></script>
	<!-- Bootstrap -->
	<script src="js/bootstrap.min.js"></script>
	<!-- Waypoints -->
	<script src="js/jquery.waypoints.min.js"></script>
	<!-- Owl Carousel -->
	<script src="js/owl.carousel.min.js"></script>
	<!-- Magnific Popup -->
	<script src="js/jquery.magnific-popup.min.js"></script>
	<script src="js/magnific-popup-options.js"></script>

	<!-- Main JS (Do not remove) -->
	<script src="js/main.js"></script>

</body>
</html>